#!/usr/bin/env bash
# Script to transfer a file from the client to a server via SSH
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

filepath="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

ssh -o StrictHostKeyChecking=no -i "$ssh_key" "$username@$server_ip" "scp -r '$filepath' ~/"

if [ $? -eq 0 ]; then
  echo "File transferred successfully!"
else
  echo "Error transferring file."
fi
