#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.
script_pid=$$
for pid in $(pgrep -f bash); do
    # Exclude the current script's PID
    if [ "$pid" != "$script_pid" ]; then
        process_name=$(ps -p "$pid" -o comm=)
        echo "$pid $process_name"
    fi
done
