#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name, of processes whose name contain the word bash
pgrep -af bash | while read -r line; do
    pid=$(echo "$line" | awk '{print $1}')
    process_name=$(echo "$line" | awk '{$1=""; print $0}')
    echo "$pid $process_name"
done
